#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${PROJECT_ROOT}/scripts/timing.sh"
source "${PROJECT_ROOT}/scripts/wandb.sh"
THREESTUDIO_DIR="${PROJECT_ROOT}/threestudio"
OBJECT_B_NAME="object_B"
OBJECT_B_DIR="${PROJECT_ROOT}/dataset/${OBJECT_B_NAME}"
GPU=2
MAX_STEPS=10000
SEED=42
GUIDANCE_SCALE=75.0
LAMBDA_SPARSITY=10.0

# object B - main
PROMPT="a zoomed out DSLR product photo of a single umbrella-shaped mushroom, one broad beige brown cap with subtle radial grooves, visible gills under the cap, one straight thick white stem with a small ring, full object, centered, clean silhouette, natural matte surface, detailed organic texture, plain background"
NEGATIVE_PROMPT="extra cap, extra stem, stacked body, multiple mushrooms, deformed, distorted, broken geometry, floating parts, messy background, cropped, blurry, text, watermark"

NEGATIVE_PROMPT_ARGS=()
if [ -n "$NEGATIVE_PROMPT" ]; then
  NEGATIVE_PROMPT_ARGS=(system.prompt_processor.negative_prompt="$NEGATIVE_PROMPT")
fi

TRAIN_ARGS=(
  --config configs/dreamfusion-sd.yaml
  --train
  --gpu 0
  seed=$SEED
  exp_root_dir="../dataset/${OBJECT_B_NAME}"
  name=.
  tag=.
  use_timestamp=false
  trainer.max_steps=$MAX_STEPS
  system.prompt_processor.pretrained_model_name_or_path="stable-diffusion-v1-5/stable-diffusion-v1-5"
  system.guidance.pretrained_model_name_or_path="stable-diffusion-v1-5/stable-diffusion-v1-5"
  system.prompt_processor.prompt="$PROMPT"
  "${NEGATIVE_PROMPT_ARGS[@]}"
  system.guidance.guidance_scale=$GUIDANCE_SCALE
  system.loss.lambda_sparsity=$LAMBDA_SPARSITY
)

EXPORT_ARGS=(
  --config "${OBJECT_B_DIR}/configs/parsed.yaml"
  --export
  --gpu 0
  resume="${OBJECT_B_DIR}/ckpts/last.ckpt"
)

source ~/miniconda3/etc/profile.d/conda.sh
conda activate cvpj1

export CUDA_HOME=$CONDA_PREFIX
export CUDA_PATH=$CONDA_PREFIX
export CUDACXX=$CONDA_PREFIX/bin/nvcc
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib:$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}
export TORCH_CUDA_ARCH_LIST="8.6"
export TCNN_CUDA_ARCHITECTURES=86
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export DIFFUSERS_OFFLINE=1

mkdir -p "$OBJECT_B_DIR"
rm -rf \
  "${OBJECT_B_DIR}/ckpts" \
  "${OBJECT_B_DIR}/configs" \
  "${OBJECT_B_DIR}/csv_logs" \
  "${OBJECT_B_DIR}/tb_logs" \
  "${OBJECT_B_DIR}/save"

# OBJECT_B_DIR: stores one Object B training run and its exported virtual asset without timestamp subdirectories.
# rm -rf: removes derived artifacts from an earlier run so training and export cannot mix checkpoints.

cd "$THREESTUDIO_DIR"

run_timed "$OBJECT_B_NAME" threestudio_train \
env CUDA_VISIBLE_DEVICES=$GPU python launch.py "${TRAIN_ARGS[@]}"

log_metrics_to_wandb "$OBJECT_B_NAME" --profile dreamfusion "${OBJECT_B_DIR}/csv_logs"

# CUDA_VISIBLE_DEVICES: exposes one physical GPU to threestudio as logical CUDA device 0.
# --config: selects the DreamFusion Stable Diffusion configuration.
# --train: runs text-to-3D optimization.
# --gpu: selects logical CUDA device 0 from CUDA_VISIBLE_DEVICES.
# seed: fixes the random seed to make this Object B run more reproducible.
# exp_root_dir: writes Object B artifacts directly under dataset/object_B.
# name: avoids an extra named experiment directory.
# tag: avoids an extra tagged experiment directory.
# use_timestamp: prevents creation of timestamp experiment directories for this single asset.
# trainer.max_steps: runs the configured SDS optimization for MAX_STEPS steps.
# system.prompt_processor.pretrained_model_name_or_path: uses the accessible Stable Diffusion v1.5 prompt encoder.
# system.guidance.pretrained_model_name_or_path: uses the matching Stable Diffusion v1.5 guidance model.
# system.prompt_processor.prompt: defines the generated Object B virtual asset.
# system.prompt_processor.negative_prompt: discourages extra parts, duplicated structure, and broken geometry.
# system.guidance.guidance_scale: reduces overly aggressive SDS guidance to improve geometry stability.
# system.loss.lambda_sparsity: increases density sparsity to suppress bottom diffusion, floaters, and unnecessary volume density.
# log_metrics_to_wandb: uploads selected SDS, orient, sparsity, and opaque losses to WandB after training; upload failure does not change artifacts.

run_timed "$OBJECT_B_NAME" threestudio_export \
env CUDA_VISIBLE_DEVICES=$GPU python launch.py "${EXPORT_ARGS[@]}"

# CUDA_VISIBLE_DEVICES: exposes the same physical GPU used for training.
# --config: restores the exact resolved training configuration.
# --export: extracts a textured Mesh from the optimized implicit representation.
# --gpu: selects logical CUDA device 0 from CUDA_VISIBLE_DEVICES.
# resume: loads the final Object B checkpoint generated by the preceding training command.
