#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${PROJECT_ROOT}/scripts/timing.sh"
source "${PROJECT_ROOT}/scripts/wandb.sh"
OBJECT_A_NAME="object_A"
OBJECT_A_DIR="${PROJECT_ROOT}/dataset/${OBJECT_A_NAME}"
IMAGES_RAW_DIR="${OBJECT_A_DIR}/images_raw"
IMAGES_DIR="${OBJECT_A_DIR}/images"
SPARSE_DIR="${OBJECT_A_DIR}/sparse"
DATABASE_PATH="${OBJECT_A_DIR}/database.db"
OUTPUT_DIR="${OBJECT_A_DIR}/2dgs_output"
GS_DIR="${PROJECT_ROOT}/2d-gaussian-splatting"
GPU=1
PORT=6010
MAX_STEPS=15000
EVAL_INTERVAL=1000
LAMBDA_MASK=0.1
MESH_VOXEL_SIZE=0.006
MESH_SDF_TRUNC=0.024
TWODGS_PATCH="${PROJECT_ROOT}/patches/2d-gaussian-splatting-alpha-mask.patch"
TEST_ITERATIONS=()
for step in $(seq "$EVAL_INTERVAL" "$EVAL_INTERVAL" "$MAX_STEPS"); do
  TEST_ITERATIONS+=("$step")
done

ensure_2dgs_alpha_patch() {
  if grep -q "lambda_mask" "${GS_DIR}/arguments/__init__.py"; then
    return
  fi
  git -C "$GS_DIR" apply "$TWODGS_PATCH"
}

source ~/miniconda3/etc/profile.d/conda.sh
conda activate cvpj1
export NUMBA_CACHE_DIR=/tmp/numba_cache
export U2NET_HOME="${PROJECT_ROOT}/.cache/rembg"
mkdir -p "$NUMBA_CACHE_DIR"
mkdir -p "$U2NET_HOME"

cd "$PROJECT_ROOT"

run_timed "$OBJECT_A_NAME" preprocess \
  python scripts/preprocess_image.py "$IMAGES_RAW_DIR" objectA

# scripts/preprocess_image.py: reads original images from images_raw and overwrites matching transparent RGBA PNG files in images.
# objectA: uses BRIA-RMBG 2.0, keeps only the largest foreground component, and writes a hard alpha mask.

rm -f "$DATABASE_PATH"
rm -rf "$SPARSE_DIR" "$OUTPUT_DIR"
mkdir -p "$SPARSE_DIR"

# DATABASE_PATH: removed because COLMAP features and matches depend on the current foreground images.
# SPARSE_DIR: removed because camera poses must be rebuilt from the current foreground images.
# OUTPUT_DIR: removed because the 2DGS model must be trained from the rebuilt COLMAP scene.

unset LD_LIBRARY_PATH

run_timed "$OBJECT_A_NAME" colmap_feature_extractor \
colmap feature_extractor \
  --database_path "$DATABASE_PATH" \
  --image_path "$IMAGES_DIR" \
  --ImageReader.single_camera 1 \
  --ImageReader.camera_model PINHOLE \
  --FeatureExtraction.use_gpu 1 \
  --FeatureExtraction.gpu_index "$GPU"

# --database_path: writes extracted local image features to the Object A COLMAP database.
# --image_path: reads transparent foreground PNG files generated by scripts/preprocess_image.py.
# --ImageReader.single_camera: shares one intrinsic camera model across images captured by the same phone and focal length.
# --ImageReader.camera_model: uses PINHOLE because the current 2DGS loader supports undistorted PINHOLE camera models.
# --FeatureExtraction.use_gpu: enables GPU feature extraction.
# --FeatureExtraction.gpu_index: selects the physical GPU used by COLMAP feature extraction.

run_timed "$OBJECT_A_NAME" colmap_exhaustive_matcher \
colmap exhaustive_matcher \
  --database_path "$DATABASE_PATH" \
  --FeatureMatching.use_gpu 1 \
  --FeatureMatching.gpu_index "$GPU"

# --database_path: reads extracted features and stores pairwise feature matches.
# --FeatureMatching.use_gpu: enables GPU feature matching.
# --FeatureMatching.gpu_index: selects the physical GPU used by COLMAP feature matching.

run_timed "$OBJECT_A_NAME" colmap_mapper \
colmap mapper \
  --database_path "$DATABASE_PATH" \
  --image_path "$IMAGES_DIR" \
  --output_path "$SPARSE_DIR"

# --database_path: reads features and matches from the Object A COLMAP database.
# --image_path: reads the same transparent foreground PNG files used during feature extraction.
# --output_path: writes camera poses and the sparse point cloud to sparse/0.

run_timed "$OBJECT_A_NAME" colmap_model_analyzer \
colmap model_analyzer \
  --path "${SPARSE_DIR}/0"

# --path: reads the reconstructed COLMAP sparse model and prints registration and reprojection statistics.

export CUDA_HOME=$CONDA_PREFIX
export CUDA_PATH=$CONDA_PREFIX
export CUDACXX=$CONDA_PREFIX/bin/nvcc
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib:$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}
export TORCH_CUDA_ARCH_LIST="8.6"
export TCNN_CUDA_ARCHITECTURES=86

ensure_2dgs_alpha_patch

cd "$GS_DIR"

run_timed "$OBJECT_A_NAME" 2dgs_train \
env CUDA_VISIBLE_DEVICES=$GPU python train.py \
  -s "$OBJECT_A_DIR" \
  -m "$OUTPUT_DIR" \
  --iterations "$MAX_STEPS" \
  --position_lr_max_steps "$MAX_STEPS" \
  --save_iterations "$MAX_STEPS" \
  --test_iterations "${TEST_ITERATIONS[@]}" \
  --port "$PORT" \
  --lambda_mask "$LAMBDA_MASK"

log_metrics_to_wandb "$OBJECT_A_NAME" --profile twodgs "$OUTPUT_DIR"

# CUDA_VISIBLE_DEVICES: exposes one physical GPU to 2DGS as logical CUDA device 0.
# -s: reads images and sparse/0 from the Object A scene directory.
# -m: writes checkpoints, logs, and training artifacts to 2dgs_output.
# --iterations: runs Object A training for MAX_STEPS steps.
# --position_lr_max_steps: matches the position learning-rate schedule to the shortened training length.
# --save_iterations: saves only the final checkpoint for the configured MAX_STEPS run.
# --test_iterations: evaluates every EVAL_INTERVAL steps.
# --port: avoids the default 2DGS network GUI port when another 2DGS job is running.
# --lambda_mask: constrains rendered opacity to the shoe alpha mask, which helps stabilize low-texture sole geometry.
# log_metrics_to_wandb: uploads selected 2DGS loss and PSNR metrics to WandB after training; upload failure does not change artifacts.

run_timed "$OBJECT_A_NAME" 2dgs_render_export \
env CUDA_VISIBLE_DEVICES=$GPU python render.py \
  -s "$OBJECT_A_DIR" \
  -m "$OUTPUT_DIR" \
  --iteration "$MAX_STEPS" \
  --num_cluster 1 \
  --voxel_size "$MESH_VOXEL_SIZE" \
  --sdf_trunc "$MESH_SDF_TRUNC"

# CUDA_VISIBLE_DEVICES: exposes the same physical GPU used for training.
# -s: reads the Object A source scene.
# -m: loads the trained 2DGS model and writes render artifacts.
# --iteration: loads the final MAX_STEPS checkpoint and exports rendered views, fuse.ply, and fuse_post.ply.
# --num_cluster: keeps only the largest connected mesh component in fuse_post.ply.
# --voxel_size/--sdf_trunc: use slightly smoother TSDF fusion to reduce fragmented sole surfaces.
