experiment_name: unet_ce_dice
output_dir: outputs/unet_ce_dice

seed: 42
device: auto

data:
  root: ../dataset/oxford-iiit-pet
  image_size: 256
  val_ratio: 0.2
  num_workers: 0

model:
  name: unet
  in_channels: 3
  num_classes: 3
  base_channels: 64

train:
  epochs: 50
  batch_size: 8
  optimizer: adamw
  lr: 0.001
  weight_decay: 0.0001
  scheduler: cosine
  save_metric: val_mIoU
  amp: false

loss:
  name: ce_dice
  ce_weight: 1.0
  dice_weight: 1.0

wandb:
  entity: fudan-university-CS50028
  project: mid-project
