gpu_id: 0
run_name: act_B
step: "050000"
dataset_repo: calvin_task_ABC_D_lerobot_3_4
dataset_root: dataset/calvin_task_ABC_D/calvin_task_ABC_D_lerobot_3_4
batch_size: 64
num_workers: 4
tolerance_s: 0.001
