gpu_id: 1
run_name: act_ABC
dataset_repo: calvin_ABC_v30
dataset_root: dataset/calvin_ABC_v30
wandb_project: final-project
wandb_entity: fudan-university-CS50028
steps: 50000
batch_size: 64
save_freq: 10000
log_freq: 100
tolerance_s: 0.001
disable_artifact: true
