gpu_id: 0
run_name: act_B
dataset_repo: calvin_task_ABC_D_lerobot_1_4
dataset_root: dataset/calvin_task_ABC_D/calvin_task_ABC_D_lerobot_1_4
wandb_project: final-project
wandb_entity: fudan-university-CS50028
steps: 50000
batch_size: 64
save_freq: 10000
log_freq: 1
tolerance_s: 0.001
disable_artifact: true
